name: Build and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get Node
      uses: actions/setup-node@v4
    - name: Get Angular
      run: npm install --global @angular/cli
      working-directory: myblog/
    - name: Installing dependencies
      run: npm install
      working-directory: myblog/
    - name: Building
      run: npm run build
      working-directory: myblog/
    # - name: Testing
    #   run: npm run test
    #   working-directory: myblog/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: myblog/dist/myblog/browser/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}