name: myblog

on:
  push:
    branches:
      - myblog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        base_href: /myblog/
        angular_project_dir: myblog/
        angular_dist_build_folder: myblog/dist/myblog/browser

permissions:
  contents: write